version: "3.8"
services:
    appender-rabbitmq:
        image: rabbitmq: 4.0.4
        container_name: appender-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volume:
            - .rabbitmq
