version: "3.8"

services:
    appender-rabbitmq:
        image: rabbitmq:management
        container_name: appender-rabbitmq
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
        ports:
            - 5672:5672
            - 15672:15672